# -*- coding: utf-8 -*-
"""GIAIC-project-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeajlr2WZS5-4a7Il-jLRA9GSNjccNcV

# **mad libs game with single story**
"""

def mad_libs():
    # Welcome message
    print("Welcome to the Mad Libs game!")
    print("Fill in the blanks to create your story.\n")

    # Asking for user inputs
    name = input("Enter a name: ")
    place = input("Enter a place: ")
    adjective = input("Enter an adjective: ")
    noun = input("Enter a noun: ")
    verb = input("Enter a verb: ")
    animal = input("Enter an animal: ")

    # Story template
    story = (
        f"Once upon a time, {name} went to {place}. "
        f"It was a {adjective} day, and they decided to bring a {noun} with them. "
        f"While they were there, they saw a {animal} {verb}ing in the distance. "
        f"Surprised, {name} exclaimed, 'What a day to remember!'"
    )

    # Display the completed story
    print("\nYour Mad Libs story:\n")
    print(story)

# Run the Mad Libs function
mad_libs()

"""# **Mad Libs Game with Random Choice Story**"""

import random

def mad_libs():
    stories = [
        "Today, I went to the {place} and saw a {adjective} {noun} {verb}ing. It was so funny!",
        "Once upon a time, {name} found a {adjective} {noun} while walking through {place}.",
        "{name} decided to {verb} with a {adjective} {animal} at the {place}. What a day!"
    ]

    # Randomly select a story template
    story_template = random.choice(stories)

    # Collect inputs
    name = input("Enter a name: ")
    place = input("Enter a place: ")
    adjective = input("Enter an adjective: ")
    noun = input("Enter a noun: ")
    verb = input("Enter a verb: ")
    animal = input("Enter an animal: ")

    # Fill in the story template
    story = story_template.format(
        name=name, place=place, adjective=adjective,
        noun=noun, verb=verb, animal=animal
    )

    print("\nYour Mad Libs story:\n")
    print(story)

# Run the game
mad_libs()

